spring:
  datasource:
    username: root
    password: 112121
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/account_db?useUnicode=true&useSSL=false&characterEncoding=utf8
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
